// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd_8H3DPBIrtPq8APHmPO_XV2FKLc_D0Q',
    appId: '1:881855520522:web:e664c3c864f0db0a39e4f3',
    messagingSenderId: '881855520522',
    projectId: 'receiptscanner-bf686',
    authDomain: 'receiptscanner-bf686.firebaseapp.com',
    storageBucket: 'receiptscanner-bf686.firebasestorage.app',
    measurementId: 'G-6D7M3K3PNZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByjWrl4NT92jMJIc66E5QiiKoeT6X8bhI',
    appId: '1:881855520522:android:55388d50b826779339e4f3',
    messagingSenderId: '881855520522',
    projectId: 'receiptscanner-bf686',
    storageBucket: 'receiptscanner-bf686.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQmCEtg5p98B6TFOpZx_MYxqOd_tQLt5g',
    appId: '1:881855520522:ios:794b0b891536a92239e4f3',
    messagingSenderId: '881855520522',
    projectId: 'receiptscanner-bf686',
    storageBucket: 'receiptscanner-bf686.firebasestorage.app',
    iosClientId: '881855520522-t6ic5si734l3pcnlf0k29292aa7jhf2h.apps.googleusercontent.com',
    iosBundleId: 'com.example.sc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQmCEtg5p98B6TFOpZx_MYxqOd_tQLt5g',
    appId: '1:881855520522:ios:794b0b891536a92239e4f3',
    messagingSenderId: '881855520522',
    projectId: 'receiptscanner-bf686',
    storageBucket: 'receiptscanner-bf686.firebasestorage.app',
    iosClientId: '881855520522-t6ic5si734l3pcnlf0k29292aa7jhf2h.apps.googleusercontent.com',
    iosBundleId: 'com.example.sc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAd_8H3DPBIrtPq8APHmPO_XV2FKLc_D0Q',
    appId: '1:881855520522:web:1b7026432aac1de339e4f3',
    messagingSenderId: '881855520522',
    projectId: 'receiptscanner-bf686',
    authDomain: 'receiptscanner-bf686.firebaseapp.com',
    storageBucket: 'receiptscanner-bf686.firebasestorage.app',
    measurementId: 'G-BDCLK36XDL',
  );

}